### YamlMime:ManagedReference
items:
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config
  commentId: T:Org.BouncyCastle.Math.EC.ECCurve.Config
  id: ECCurve.Config
  parent: Org.BouncyCastle.Math.EC
  children:
  - Org.BouncyCastle.Math.EC.ECCurve.Config.coord
  - Org.BouncyCastle.Math.EC.ECCurve.Config.Create
  - Org.BouncyCastle.Math.EC.ECCurve.Config.endomorphism
  - Org.BouncyCastle.Math.EC.ECCurve.Config.multiplier
  - Org.BouncyCastle.Math.EC.ECCurve.Config.outer
  - Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem(System.Int32)
  - Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism(ECEndomorphism)
  - Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier(ECMultiplier)
  langs:
  - csharp
  - vb
  name: ECCurve.Config
  nameWithType: ECCurve.Config
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config
  type: Class
  source:
    id: Config
    path: ''
    startLine: 18059
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: public class Config
    content.vb: Public Class Config
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.ReferenceEquals(System.Object,System.Object)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.outer
  commentId: F:Org.BouncyCastle.Math.EC.ECCurve.Config.outer
  id: outer
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: outer
  nameWithType: ECCurve.Config.outer
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.outer
  type: Field
  source:
    id: outer
    path: ''
    startLine: 18061
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: protected ECCurve outer
    return:
      type: Org.BouncyCastle.Math.EC.ECCurve
    content.vb: Protected outer As ECCurve
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.coord
  commentId: F:Org.BouncyCastle.Math.EC.ECCurve.Config.coord
  id: coord
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: coord
  nameWithType: ECCurve.Config.coord
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.coord
  type: Field
  source:
    id: coord
    path: ''
    startLine: 18062
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: protected int coord
    return:
      type: System.Int32
    content.vb: Protected coord As Integer
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.endomorphism
  commentId: F:Org.BouncyCastle.Math.EC.ECCurve.Config.endomorphism
  id: endomorphism
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: endomorphism
  nameWithType: ECCurve.Config.endomorphism
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.endomorphism
  type: Field
  source:
    id: endomorphism
    path: ''
    startLine: 18063
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: protected ECEndomorphism endomorphism
    return:
      type: ECEndomorphism
    content.vb: Protected endomorphism As ECEndomorphism
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.multiplier
  commentId: F:Org.BouncyCastle.Math.EC.ECCurve.Config.multiplier
  id: multiplier
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: multiplier
  nameWithType: ECCurve.Config.multiplier
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.multiplier
  type: Field
  source:
    id: multiplier
    path: ''
    startLine: 18064
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: protected ECMultiplier multiplier
    return:
      type: ECMultiplier
    content.vb: Protected multiplier As ECMultiplier
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem(System.Int32)
  commentId: M:Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem(System.Int32)
  id: SetCoordinateSystem(System.Int32)
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: SetCoordinateSystem(Int32)
  nameWithType: ECCurve.Config.SetCoordinateSystem(Int32)
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem(System.Int32)
  type: Method
  source:
    id: SetCoordinateSystem
    path: ''
    startLine: 18074
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: public ECCurve.Config SetCoordinateSystem(int coord)
    parameters:
    - id: coord
      type: System.Int32
    return:
      type: Org.BouncyCastle.Math.EC.ECCurve.Config
    content.vb: Public Function SetCoordinateSystem(coord As Integer) As ECCurve.Config
  overload: Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism(ECEndomorphism)
  commentId: M:Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism(ECEndomorphism)
  id: SetEndomorphism(ECEndomorphism)
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: SetEndomorphism(ECEndomorphism)
  nameWithType: ECCurve.Config.SetEndomorphism(ECEndomorphism)
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism(ECEndomorphism)
  type: Method
  source:
    id: SetEndomorphism
    path: ''
    startLine: 18080
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: public ECCurve.Config SetEndomorphism(ECEndomorphism endomorphism)
    parameters:
    - id: endomorphism
      type: ECEndomorphism
    return:
      type: Org.BouncyCastle.Math.EC.ECCurve.Config
    content.vb: Public Function SetEndomorphism(endomorphism As ECEndomorphism) As ECCurve.Config
  overload: Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier(ECMultiplier)
  commentId: M:Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier(ECMultiplier)
  id: SetMultiplier(ECMultiplier)
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: SetMultiplier(ECMultiplier)
  nameWithType: ECCurve.Config.SetMultiplier(ECMultiplier)
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier(ECMultiplier)
  type: Method
  source:
    id: SetMultiplier
    path: ''
    startLine: 18086
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: public ECCurve.Config SetMultiplier(ECMultiplier multiplier)
    parameters:
    - id: multiplier
      type: ECMultiplier
    return:
      type: Org.BouncyCastle.Math.EC.ECCurve.Config
    content.vb: Public Function SetMultiplier(multiplier As ECMultiplier) As ECCurve.Config
  overload: Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.Create
  commentId: M:Org.BouncyCastle.Math.EC.ECCurve.Config.Create
  id: Create
  parent: Org.BouncyCastle.Math.EC.ECCurve.Config
  langs:
  - csharp
  - vb
  name: Create()
  nameWithType: ECCurve.Config.Create()
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.Create()
  type: Method
  source:
    id: Create
    path: ''
    startLine: 18092
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Math.EC
  syntax:
    content: public ECCurve Create()
    return:
      type: Org.BouncyCastle.Math.EC.ECCurve
    content.vb: Public Function Create As ECCurve
  overload: Org.BouncyCastle.Math.EC.ECCurve.Config.Create*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Org.BouncyCastle.Math.EC
  commentId: N:Org.BouncyCastle.Math.EC
  name: Org.BouncyCastle.Math.EC
  nameWithType: Org.BouncyCastle.Math.EC
  fullName: Org.BouncyCastle.Math.EC
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Org.BouncyCastle.Math.EC.ECCurve
  commentId: T:Org.BouncyCastle.Math.EC.ECCurve
  parent: Org.BouncyCastle.Math.EC
  name: ECCurve
  nameWithType: ECCurve
  fullName: Org.BouncyCastle.Math.EC.ECCurve
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: ECEndomorphism
  isExternal: true
  name: ECEndomorphism
  nameWithType: ECEndomorphism
  fullName: ECEndomorphism
- uid: ECMultiplier
  isExternal: true
  name: ECMultiplier
  nameWithType: ECMultiplier
  fullName: ECMultiplier
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem*
  commentId: Overload:Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem
  name: SetCoordinateSystem
  nameWithType: ECCurve.Config.SetCoordinateSystem
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.SetCoordinateSystem
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config
  commentId: T:Org.BouncyCastle.Math.EC.ECCurve.Config
  parent: Org.BouncyCastle.Math.EC
  name: ECCurve.Config
  nameWithType: ECCurve.Config
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism*
  commentId: Overload:Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism
  name: SetEndomorphism
  nameWithType: ECCurve.Config.SetEndomorphism
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.SetEndomorphism
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier*
  commentId: Overload:Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier
  name: SetMultiplier
  nameWithType: ECCurve.Config.SetMultiplier
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.SetMultiplier
- uid: Org.BouncyCastle.Math.EC.ECCurve.Config.Create*
  commentId: Overload:Org.BouncyCastle.Math.EC.ECCurve.Config.Create
  name: Create
  nameWithType: ECCurve.Config.Create
  fullName: Org.BouncyCastle.Math.EC.ECCurve.Config.Create
