### YamlMime:ManagedReference
items:
- uid: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser
  commentId: T:Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser
  id: IAsn1ApplicationSpecificParser
  parent: Org.BouncyCastle.Asn1
  children:
  - Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject
  langs:
  - csharp
  - vb
  name: IAsn1ApplicationSpecificParser
  nameWithType: IAsn1ApplicationSpecificParser
  fullName: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser
  type: Interface
  source:
    id: IAsn1ApplicationSpecificParser
    path: ''
    startLine: 24483
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Asn1
  syntax:
    content: 'public interface IAsn1ApplicationSpecificParser : IAsn1Convertible'
    content.vb: >-
      Public Interface IAsn1ApplicationSpecificParser
          Inherits IAsn1Convertible
  inheritedMembers:
  - Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject
  commentId: M:Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject
  id: ReadObject
  parent: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser
  langs:
  - csharp
  - vb
  name: ReadObject()
  nameWithType: IAsn1ApplicationSpecificParser.ReadObject()
  fullName: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject()
  type: Method
  source:
    id: ReadObject
    path: ''
    startLine: 24486
  assemblies:
  - cs.temp.dll
  namespace: Org.BouncyCastle.Asn1
  syntax:
    content: IAsn1Convertible ReadObject()
    return:
      type: Org.BouncyCastle.Asn1.IAsn1Convertible
    content.vb: Function ReadObject As IAsn1Convertible
  overload: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject*
references:
- uid: Org.BouncyCastle.Asn1
  commentId: N:Org.BouncyCastle.Asn1
  name: Org.BouncyCastle.Asn1
  nameWithType: Org.BouncyCastle.Asn1
  fullName: Org.BouncyCastle.Asn1
- uid: Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object
  commentId: M:Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object
  parent: Org.BouncyCastle.Asn1.IAsn1Convertible
  name: ToAsn1Object()
  nameWithType: IAsn1Convertible.ToAsn1Object()
  fullName: Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object()
  spec.csharp:
  - uid: Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object
    name: ToAsn1Object
    nameWithType: IAsn1Convertible.ToAsn1Object
    fullName: Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object
    name: ToAsn1Object
    nameWithType: IAsn1Convertible.ToAsn1Object
    fullName: Org.BouncyCastle.Asn1.IAsn1Convertible.ToAsn1Object
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Org.BouncyCastle.Asn1.IAsn1Convertible
  commentId: T:Org.BouncyCastle.Asn1.IAsn1Convertible
  parent: Org.BouncyCastle.Asn1
  name: IAsn1Convertible
  nameWithType: IAsn1Convertible
  fullName: Org.BouncyCastle.Asn1.IAsn1Convertible
- uid: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject*
  commentId: Overload:Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject
  name: ReadObject
  nameWithType: IAsn1ApplicationSpecificParser.ReadObject
  fullName: Org.BouncyCastle.Asn1.IAsn1ApplicationSpecificParser.ReadObject
