### YamlMime:ManagedReference
items:
- uid: Org.BouncyCastle.Security
  commentId: N:Org.BouncyCastle.Security
  id: Org.BouncyCastle.Security
  children:
  - Org.BouncyCastle.Security.DigestUtilities
  - Org.BouncyCastle.Security.GeneralSecurityException
  - Org.BouncyCastle.Security.InvalidKeyException
  - Org.BouncyCastle.Security.InvalidParameterException
  - Org.BouncyCastle.Security.KeyException
  - Org.BouncyCastle.Security.MacUtilities
  - Org.BouncyCastle.Security.PublicKeyFactory
  - Org.BouncyCastle.Security.SecureRandom
  - Org.BouncyCastle.Security.SecurityUtilityException
  - Org.BouncyCastle.Security.SignatureException
  - Org.BouncyCastle.Security.SignerUtilities
  langs:
  - csharp
  - vb
  name: Org.BouncyCastle.Security
  nameWithType: Org.BouncyCastle.Security
  fullName: Org.BouncyCastle.Security
  type: Namespace
  assemblies:
  - cs.temp.dll
references:
- uid: Org.BouncyCastle.Security.DigestUtilities
  commentId: T:Org.BouncyCastle.Security.DigestUtilities
  name: DigestUtilities
  nameWithType: DigestUtilities
  fullName: Org.BouncyCastle.Security.DigestUtilities
- uid: Org.BouncyCastle.Security.KeyException
  commentId: T:Org.BouncyCastle.Security.KeyException
  parent: Org.BouncyCastle.Security
  name: KeyException
  nameWithType: KeyException
  fullName: Org.BouncyCastle.Security.KeyException
- uid: Org.BouncyCastle.Security.PublicKeyFactory
  commentId: T:Org.BouncyCastle.Security.PublicKeyFactory
  name: PublicKeyFactory
  nameWithType: PublicKeyFactory
  fullName: Org.BouncyCastle.Security.PublicKeyFactory
- uid: Org.BouncyCastle.Security.InvalidKeyException
  commentId: T:Org.BouncyCastle.Security.InvalidKeyException
  name: InvalidKeyException
  nameWithType: InvalidKeyException
  fullName: Org.BouncyCastle.Security.InvalidKeyException
- uid: Org.BouncyCastle.Security.SecurityUtilityException
  commentId: T:Org.BouncyCastle.Security.SecurityUtilityException
  name: SecurityUtilityException
  nameWithType: SecurityUtilityException
  fullName: Org.BouncyCastle.Security.SecurityUtilityException
- uid: Org.BouncyCastle.Security.SignerUtilities
  commentId: T:Org.BouncyCastle.Security.SignerUtilities
  name: SignerUtilities
  nameWithType: SignerUtilities
  fullName: Org.BouncyCastle.Security.SignerUtilities
- uid: Org.BouncyCastle.Security.GeneralSecurityException
  commentId: T:Org.BouncyCastle.Security.GeneralSecurityException
  parent: Org.BouncyCastle.Security
  name: GeneralSecurityException
  nameWithType: GeneralSecurityException
  fullName: Org.BouncyCastle.Security.GeneralSecurityException
- uid: Org.BouncyCastle.Security.MacUtilities
  commentId: T:Org.BouncyCastle.Security.MacUtilities
  name: MacUtilities
  nameWithType: MacUtilities
  fullName: Org.BouncyCastle.Security.MacUtilities
- uid: Org.BouncyCastle.Security.SignatureException
  commentId: T:Org.BouncyCastle.Security.SignatureException
  name: SignatureException
  nameWithType: SignatureException
  fullName: Org.BouncyCastle.Security.SignatureException
- uid: Org.BouncyCastle.Security.InvalidParameterException
  commentId: T:Org.BouncyCastle.Security.InvalidParameterException
  name: InvalidParameterException
  nameWithType: InvalidParameterException
  fullName: Org.BouncyCastle.Security.InvalidParameterException
- uid: Org.BouncyCastle.Security.SecureRandom
  commentId: T:Org.BouncyCastle.Security.SecureRandom
  parent: Org.BouncyCastle.Security
  name: SecureRandom
  nameWithType: SecureRandom
  fullName: Org.BouncyCastle.Security.SecureRandom
- uid: Org.BouncyCastle.Security
  commentId: N:Org.BouncyCastle.Security
  name: Org.BouncyCastle.Security
  nameWithType: Org.BouncyCastle.Security
  fullName: Org.BouncyCastle.Security
