### YamlMime:ManagedReference
items:
- uid: Winpeak.Client.Utils.SceneSettingsController
  commentId: T:Winpeak.Client.Utils.SceneSettingsController
  id: SceneSettingsController
  parent: Winpeak.Client.Utils
  children:
  - Winpeak.Client.Utils.SceneSettingsController.IsLocal
  - Winpeak.Client.Utils.SceneSettingsController.IsNetwork
  - Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints
  - Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode
  - Winpeak.Client.Utils.SceneSettingsController.Test
  - Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition
  - Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets
  - Winpeak.Client.Utils.SceneSettingsController.UseSmooth
  langs:
  - csharp
  - vb
  name: SceneSettingsController
  nameWithType: SceneSettingsController
  fullName: Winpeak.Client.Utils.SceneSettingsController
  type: Class
  source:
    id: SceneSettingsController
    path: ''
    startLine: 163
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: 'public class SceneSettingsController : MonoBehaviour'
    content.vb: >-
      Public Class SceneSettingsController
          Inherits MonoBehaviour
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Winpeak.Client.Utils.SceneSettingsController.Test
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.Test
  id: Test
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: Test
  nameWithType: SceneSettingsController.Test
  fullName: Winpeak.Client.Utils.SceneSettingsController.Test
  type: Property
  source:
    id: Test
    path: ''
    startLine: 185
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public bool Test { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property Test As Boolean
  overload: Winpeak.Client.Utils.SceneSettingsController.Test*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Winpeak.Client.Utils.SceneSettingsController.IsNetwork
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.IsNetwork
  id: IsNetwork
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: IsNetwork
  nameWithType: SceneSettingsController.IsNetwork
  fullName: Winpeak.Client.Utils.SceneSettingsController.IsNetwork
  type: Property
  source:
    id: IsNetwork
    path: ''
    startLine: 187
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public bool IsNetwork { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property IsNetwork As Boolean
  overload: Winpeak.Client.Utils.SceneSettingsController.IsNetwork*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Winpeak.Client.Utils.SceneSettingsController.IsLocal
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.IsLocal
  id: IsLocal
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: IsLocal
  nameWithType: SceneSettingsController.IsLocal
  fullName: Winpeak.Client.Utils.SceneSettingsController.IsLocal
  type: Property
  source:
    id: IsLocal
    path: ''
    startLine: 189
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public bool IsLocal { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property IsLocal As Boolean
  overload: Winpeak.Client.Utils.SceneSettingsController.IsLocal*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints
  id: ShowWaypoints
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: ShowWaypoints
  nameWithType: SceneSettingsController.ShowWaypoints
  fullName: Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints
  type: Property
  source:
    id: ShowWaypoints
    path: ''
    startLine: 191
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public bool ShowWaypoints { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property ShowWaypoints As Boolean
  overload: Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Winpeak.Client.Utils.SceneSettingsController.UseSmooth
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.UseSmooth
  id: UseSmooth
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: UseSmooth
  nameWithType: SceneSettingsController.UseSmooth
  fullName: Winpeak.Client.Utils.SceneSettingsController.UseSmooth
  type: Property
  source:
    id: UseSmooth
    path: ''
    startLine: 193
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public bool UseSmooth { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property UseSmooth As Boolean
  overload: Winpeak.Client.Utils.SceneSettingsController.UseSmooth*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition
  id: UseApproximateStartPosition
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: UseApproximateStartPosition
  nameWithType: SceneSettingsController.UseApproximateStartPosition
  fullName: Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition
  type: Property
  source:
    id: UseApproximateStartPosition
    path: ''
    startLine: 195
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public bool UseApproximateStartPosition { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property UseApproximateStartPosition As Boolean
  overload: Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets
  id: UseImportantPackets
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: UseImportantPackets
  nameWithType: SceneSettingsController.UseImportantPackets
  fullName: Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets
  type: Property
  source:
    id: UseImportantPackets
    path: ''
    startLine: 197
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public bool UseImportantPackets { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property UseImportantPackets As Boolean
  overload: Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode
  commentId: P:Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode
  id: ShowWaypointsMode
  parent: Winpeak.Client.Utils.SceneSettingsController
  langs:
  - csharp
  - vb
  name: ShowWaypointsMode
  nameWithType: SceneSettingsController.ShowWaypointsMode
  fullName: Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode
  type: Property
  source:
    id: ShowWaypointsMode
    path: ''
    startLine: 199
  assemblies:
  - cs.temp.dll
  namespace: Winpeak.Client.Utils
  syntax:
    content: public WaypointsShowMode ShowWaypointsMode { get; }
    parameters: []
    return:
      type: Winpeak.Client.Utils.WaypointsShowMode
    content.vb: Public ReadOnly Property ShowWaypointsMode As WaypointsShowMode
  overload: Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Winpeak.Client.Utils
  commentId: N:Winpeak.Client.Utils
  name: Winpeak.Client.Utils
  nameWithType: Winpeak.Client.Utils
  fullName: Winpeak.Client.Utils
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Winpeak.Client.Utils.SceneSettingsController.Test*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.Test
  name: Test
  nameWithType: SceneSettingsController.Test
  fullName: Winpeak.Client.Utils.SceneSettingsController.Test
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Winpeak.Client.Utils.SceneSettingsController.IsNetwork*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.IsNetwork
  name: IsNetwork
  nameWithType: SceneSettingsController.IsNetwork
  fullName: Winpeak.Client.Utils.SceneSettingsController.IsNetwork
- uid: Winpeak.Client.Utils.SceneSettingsController.IsLocal*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.IsLocal
  name: IsLocal
  nameWithType: SceneSettingsController.IsLocal
  fullName: Winpeak.Client.Utils.SceneSettingsController.IsLocal
- uid: Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints
  name: ShowWaypoints
  nameWithType: SceneSettingsController.ShowWaypoints
  fullName: Winpeak.Client.Utils.SceneSettingsController.ShowWaypoints
- uid: Winpeak.Client.Utils.SceneSettingsController.UseSmooth*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.UseSmooth
  name: UseSmooth
  nameWithType: SceneSettingsController.UseSmooth
  fullName: Winpeak.Client.Utils.SceneSettingsController.UseSmooth
- uid: Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition
  name: UseApproximateStartPosition
  nameWithType: SceneSettingsController.UseApproximateStartPosition
  fullName: Winpeak.Client.Utils.SceneSettingsController.UseApproximateStartPosition
- uid: Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets
  name: UseImportantPackets
  nameWithType: SceneSettingsController.UseImportantPackets
  fullName: Winpeak.Client.Utils.SceneSettingsController.UseImportantPackets
- uid: Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode*
  commentId: Overload:Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode
  name: ShowWaypointsMode
  nameWithType: SceneSettingsController.ShowWaypointsMode
  fullName: Winpeak.Client.Utils.SceneSettingsController.ShowWaypointsMode
- uid: Winpeak.Client.Utils.WaypointsShowMode
  commentId: T:Winpeak.Client.Utils.WaypointsShowMode
  parent: Winpeak.Client.Utils
  name: WaypointsShowMode
  nameWithType: WaypointsShowMode
  fullName: Winpeak.Client.Utils.WaypointsShowMode
